// Generated by scripts/sync-phase-colors.py; edit docs/ui-phase-colors.json.
pub fn rgb(phase: &str, dark: bool) -> [u8; 3] {
    match (phase, dark) {
        ("idle", false) => [132, 145, 167],
        ("idle", true) => [145, 160, 183],
        ("working", false) => [23, 149, 127],
        ("working", true) => [44, 157, 136],
        ("thinking", false) => [143, 87, 198],
        ("thinking", true) => [172, 120, 221],
        ("tool", false) => [63, 127, 214],
        ("tool", true) => [98, 156, 239],
        ("complete", false) => [33, 147, 85],
        ("complete", true) => [68, 173, 118],
        ("interrupted", false) => [177, 118, 31],
        ("interrupted", true) => [217, 164, 76],
        ("unknown", false) => [137, 87, 18],
        ("unknown", true) => [224, 176, 98],
        (_, true) => rgb("idle", true),
        _ => rgb("idle", false),
    }
}
