(() => {
  let records=null, busy=false, error='', statuses={};
  const statusLabels={success:'已完成',running:'运行中',failed:'调用失败，请检查登录、模型及代理',timeout:'调用超时',interrupted:'执行中断','skipped-overlap':'同账户任务运行中，已跳过'};
  const draw=()=>{if(state.page==='settings'&&state.settingsTab==='wakeups')renderSettings();};
  async function refresh(){try{records=await api('wakeups.list');}catch(e){error=e.message??String(e);}draw();}
  function html(){return `<div class="card"><h2>定时唤醒</h2><p class="muted">部署到本机或 SSH Linux 服务器，使用目标机器已登录的订阅 CLI。每天按目标机器时区执行；错过时刻不补发，退出 Aieyes 后继续运行。</p><p class="tiny muted">任务草稿独立保存；修改后需要更新部署。本机任务在用户登录期间执行。</p><div class="actions"><button id="wake-add" class="primary" ${busy?'disabled':''}>＋ 新建任务</button><button id="wake-refresh" ${busy?'disabled':''}>刷新列表</button></div>${error?`<p class="error" role="alert">${escapeHTML(error)}</p>`:''}</div>${records===null?'<p>正在读取…</p>':!records.length?'<div class="empty">尚未配置定时任务</div>':records.map(r=>{
    const t=r.task,d=r.deployment,s=statuses[t.id],last=s?.history?.[0];
    return `<div class="card wake-task"><div class="between"><h3>${escapeHTML(t.name)}</h3><span>${d?(d.state==='pending-removal'?'待移除':d.state==='deployment-unconfirmed'?'部署待确认':d.enabled?'已部署':'已停用'):'未部署'}</span></div><p>${escapeHTML(t.times.join('、'))} · ${escapeHTML(t.model)} · ${escapeHTML(t.effort||'模型默认 effort')}</p><p class="tiny muted">${escapeHTML(d?.target??'位置由数据源决定')} · ${escapeHTML(s?.timezone??d?.timezone??'跟随目标机器时区')}${d?.changed?' · 有尚未部署的更改':''}</p>${s?`<p class="tiny">${s.installed?'系统任务存在':'系统任务缺失'} · 下次 ${date(s.nextRunAt)}</p>`:''}${last?`<p class="tiny">${date(last.startedAt)} · ${escapeHTML(statusLabels[last.status]??last.status)} · ${escapeHTML(last.model)} / ${escapeHTML(last.effort||'默认')}</p>`:''}<div class="actions">${[['edit','编辑'],['deploy',d?'更新部署':'部署'],...(d?[[d.enabled?'disable':'enable',d.enabled?'停用':'启用'],['run','立即运行'],['status','状态与记录'],['remove','移除自动任务']]:[['delete','删除草稿']])].map(([a,label])=>`<button data-wake-action="${a}" data-wake-id="${escapeHTML(t.id)}" ${busy?'disabled':''}>${label}</button>`).join('')}</div></div>`;
  }).join('')}`;}
  async function action(id,kind){if(busy)return;busy=true;error='';draw();try{const result=await api('wakeups.'+kind,{id});if(kind==='status'){statuses[id]=result;historyDialog(id,result);}if(!['status','run','history'].includes(kind))delete statuses[id];if(kind==='run')notify('已启动一次唤醒，可刷新状态查看结果');await refresh();}catch(e){error=e.message??String(e);await refresh();}finally{busy=false;draw();}}
  function historyDialog(id,s){quotaDialog('运行记录',`<p>${escapeHTML(s.timezone)} · 下次 ${date(s.nextRunAt)}</p>${(s.history??[]).map(h=>`<div class="list-row"><span>${date(h.startedAt)}</span><span>${escapeHTML(statusLabels[h.status]??h.status)}</span><span>${escapeHTML(h.model)} / ${escapeHTML(h.effort||'默认')}</span></div>`).join('')||'<p>还没有运行记录。</p>'}`);}
  function edit(existing){
    const task=structuredClone(existing??{id:'',name:'订阅唤醒',sourceId:'',times:['08:00'],model:'',effort:'low',prompt:'Hi. Reply only OK. Do not use any tools.',binary:''});
    const sources=state.settings.sources.filter(s=>s.enabled&&s.accountId&&['codex','claude','agy'].includes(s.provider)&&(!s.hostId||state.settings.hosts.some(h=>h.id===s.hostId&&h.enabled)));
    if(!sources.length){notify('请先添加并保存已关联订阅账户的本机或服务器数据源','error');return;}
    if(!task.sourceId)task.sourceId=sources[0].id;
    const values=f=>({...task,name:f.get('name').trim(),sourceId:f.get('sourceId'),times:f.get('times').split(/[,，、\s]+/).filter(Boolean),model:f.get('model').trim(),effort:f.get('effort'),prompt:f.get('prompt'),binary:f.get('binary').trim()});
    showEditor(existing?'编辑唤醒任务':'新建唤醒任务',`${field('name','名称',task.name)}<label>账户与运行位置<select name="sourceId" id="wake-source">${sources.map(s=>option(s.id,`${s.name} · ${s.hostId?(state.settings.hosts.find(h=>h.id===s.hostId)?.name??s.hostId):'本机'}`,task.sourceId)).join('')}</select></label>${field('times','每天固定时刻（目标机器时区，逗号分隔）',task.times.join(', '),'08:00, 13:30')}${field('binary','CLI 路径（留空使用数据源配置）',task.binary)}<button id="wake-probe" type="button">读取模型与执行能力</button><p class="tiny muted" id="wake-capability">读取后按已知 API 价格推荐低价模型；保存草稿不会安装任务。</p><label>模型<input name="model" id="wake-model" list="wake-models" value="${escapeHTML(task.model)}" required><datalist id="wake-models"></datalist></label><label>Effort<select name="effort" id="wake-effort">${['','low','medium','high','xhigh','max','ultra'].map(e=>option(e,e||'模型默认（不传参数）',task.effort)).join('')}</select></label><label>提示词<textarea name="prompt" rows="3" maxlength="4000">${escapeHTML(task.prompt)}</textarea></label>`,async f=>{await api('wakeups.save',{task:values(f)});await refresh();});
    let models=[];
    const updateEffort=()=>{const m=models.find(m=>m.id===$('#wake-model').value);if(!m)return;const value=$('#wake-effort').value,efforts=m.efforts??[];$('#wake-effort').innerHTML=['',...efforts].map(e=>option(e,e||'模型默认',efforts.includes(value)?value:efforts.includes('low')?'low':'')).join('');};
    $('#wake-model').onchange=updateEffort;
    $('#wake-source').onchange=()=>{models=[];$('#wake-models').innerHTML='';$('#wake-model').value='';$('#wake-capability').textContent='位置已更改，请重新读取执行能力。';};
    $('#wake-probe').onclick=async()=>{const b=$('#wake-probe');b.disabled=true;try{const form=$('#editor-form'),t=values(new FormData(form)),previousEffort=t.effort;t.model='';t.effort='';const info=await api('wakeups.probe',{task:t});if(form!==$('#editor-form')||form.elements.sourceId.value!==t.sourceId||form.elements.binary.value.trim()!==t.binary)return;models=info.models??[];$('#wake-models').innerHTML=models.map(m=>`<option value="${escapeHTML(m.id)}">${m.referenceCost!=null?'参考成本 $'+m.referenceCost:'价格未知'}</option>`).join('');if(!$('#wake-model').value&&info.recommendedModel)$('#wake-model').value=info.recommendedModel;$('#wake-effort').innerHTML=['',...(info.efforts??[])].map(e=>option(e,e||'模型默认',(info.efforts??[]).includes(previousEffort)?previousEffort:(info.efforts??[]).includes('low')?'low':'')).join('');updateEffort();$('#wake-capability').textContent=info.timezone+' · '+info.message;}catch(e){if($('#wake-capability'))$('#wake-capability').textContent=e.message??String(e);}finally{b.disabled=false;}};
  }
  function bind(){if(records===null&&!busy){busy=true;refresh().finally(()=>{busy=false;draw();});}$('#wake-add').onclick=()=>edit();$('#wake-refresh').onclick=refresh;document.querySelectorAll('[data-wake-action]').forEach(b=>b.onclick=()=>b.dataset.wakeAction==='edit'?edit(records.find(r=>r.task.id===b.dataset.wakeId).task):action(b.dataset.wakeId,b.dataset.wakeAction));}
  window.AieyesWakeups={html,bind};
})();
