#!/usr/bin/env python3
"""Generate CSS/Rust phase colors from one table; --check verifies committed output."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
table = json.loads((root / 'docs/ui-phase-colors.json').read_text())
begin, end = '/* BEGIN GENERATED PHASE COLORS */', '/* END GENERATED PHASE COLORS */'
css = begin + '\n:root {\n' + ''.join(f'  --phase-{key}: #{value["light"]};\n' for key, value in table.items()) + '}\n'
css += '@media (prefers-color-scheme: dark) { :root {\n' + ''.join(f'  --phase-{key}: #{value["dark"]};\n' for key, value in table.items()) + '} }\n'
css += '@media (forced-colors: active) { :root {\n' + ''.join(f'  --phase-{key}: CanvasText;\n' for key in table) + '} }\n' + end
path = root / 'apps/desktop/web/tokens.css'
old = path.read_text()
updated = old[:old.index(begin)] + css + old[old.index(end) + len(end):] if begin in old else old.rstrip() + '\n\n' + css + '\n'
rust = '// Generated by scripts/sync-phase-colors.py; edit docs/ui-phase-colors.json.\n'
rust += 'pub fn rgb(phase: &str, dark: bool) -> [u8; 3] {\n    match (phase, dark) {\n'
for key, value in table.items():
    for theme, dark in [('light', 'false'), ('dark', 'true')]:
        rgb = ', '.join(str(int(value[theme][i:i+2], 16)) for i in (0, 2, 4))
        rust += f'        ("{key}", {dark}) => [{rgb}],\n'
rust += '        (_, true) => rgb("idle", true),\n        _ => rgb("idle", false),\n    }\n}\n'
rustpath = root / 'apps/desktop/src-tauri/src/phase_colors.rs'
if '--check' in sys.argv:
    assert old == updated, 'Run python3 scripts/sync-phase-colors.py to update tokens.css'
    assert rustpath.read_text() == rust, 'Rust phase table is stale'
    swift = (root / 'apps/macos/Sources/Aieyes/SessionActivity.swift').read_text()
    for key, value in table.items():
        assert f'case .{key}: return .{value["mac"]}' in swift, f'macOS mapping missing: {key}'
    print('Seven-phase CSS/Rust colors and macOS semantic mappings agree')
else:
    path.write_text(updated)
    rustpath.write_text(rust)
